In [2]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv("movies.csv")
df1= pd.read_csv("directors.csv")

In [22]:
df

,Unnamed: 0,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
0,0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday
1,1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday
2,2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday
3,3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday
4,5,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday
...,...,...,...,...,...,...,...,...,...,...,...,...
1460,4736,48363,0,3,321952,The Last Waltz,7.9,64,4809,1978,May,Monday
1461,4743,48370,27000,19,3151130,Clerks,7.4,755,5369,1994,Sep,Tuesday
1462,4748,48375,0,7,0,Rampage,6.0,131,5148,2009,Aug,Friday
1463,4749,48376,0,3,0,Slacker,6.4,77,5535,1990,Jul,Friday
1464,4768,48395,220000,14,2040920,El Mariachi,6.6,238,5097,1992,Sep,Friday

In [23]:
df.head()

,Unnamed: 0,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
0,0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday
1,1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday
2,2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday
3,3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday
4,5,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday

In [24]:
df["Actors"]

KeyError: 'Actors'

In [ ]:
a = pd.DataFrame([["A","B"],["A","B"]], columns=["a","b"])
b = pd.DataFrame([["A","B"],["A","B"]], columns=["a","c"])

In [ ]:
pd.concat((a,b), axis=0)

   a    b    c
0  A    B  NaN
1  A    B  NaN
0  A  NaN    B
1  A  NaN    B

In [ ]:
a

   a  b
0  A  B
1  A  B

In [ ]:
b

   a  c
0  A  B
1  A  B

In [ ]:
pd.concat([a,b],keys=["x","y"])

     a    b    c
x 0  A    B  NaN
  1  A    B  NaN
y 0  A  NaN    B
  1  A  NaN    B

In [ ]:
##inner concatenation
pd.concat([a,b], axis=0, join="inner")

   a
0  A
1  A
0  A
1  A

In [ ]:
##merge merges dataset side by side
users = pd.DataFrame({"userid":[1,2,3], "name":["A","B","C"]})
users

   userid name
0       1    A
1       2    B
2       3    C

In [ ]:
megs = pd.DataFrame({"userid":[1,1,2], "msg":["hello","hii","hyy"]})
megs

   userid    msg
0       1  hello
1       1    hii
2       2    hyy

In [ ]:
##conacet here would do here blunder

megs.merge(users,on="userid")

   userid    msg name
0       1  hello    A
1       1    hii    A
2       2    hyy    B

In [ ]:
users.rename(columns={"userid":"id"}, inplace=True)

In [ ]:
users

   id name
0   1    A
1   2    B
2   3    C

In [25]:
users

   id name
0   1    A
1   2    B
2   3    C

In [26]:
users.merge(megs,left_on="id", right_on="userid", how="inner")

   id name  userid    msg
0   1    A       1  hello
1   1    A       1    hii
2   2    B       2    hyy

In [27]:
users.merge(megs,left_on="id", right_on="userid", how="outer")

   id name  userid    msg
0   1    A     1.0  hello
1   1    A     1.0    hii
2   2    B     2.0    hyy
3   3    C     NaN    NaN

In [28]:
users.merge(megs,left_on="id", right_on="userid", how="left") ##keeps the data intact from left boudary

   id name  userid    msg
0   1    A     1.0  hello
1   1    A     1.0    hii
2   2    B     2.0    hyy
3   3    C     NaN    NaN

In [29]:
df

,Unnamed: 0,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
0,0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday
1,1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday
2,2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday
3,3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday
4,5,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday
...,...,...,...,...,...,...,...,...,...,...,...,...
1460,4736,48363,0,3,321952,The Last Waltz,7.9,64,4809,1978,May,Monday
1461,4743,48370,27000,19,3151130,Clerks,7.4,755,5369,1994,Sep,Tuesday
1462,4748,48375,0,7,0,Rampage,6.0,131,5148,2009,Aug,Friday
1463,4749,48376,0,3,0,Slacker,6.4,77,5535,1990,Jul,Friday
1464,4768,48395,220000,14,2040920,El Mariachi,6.6,238,5097,1992,Sep,Friday

In [30]:
df1

      Unnamed: 0      director_name    id gender
0              0      James Cameron  4762   Male
1              1     Gore Verbinski  4763   Male
2              2         Sam Mendes  4764   Male
3              3  Christopher Nolan  4765   Male
4              4     Andrew Stanton  4766   Male
...          ...                ...   ...    ...
2344        2344      Shane Carruth  7106   Male
2345        2345   Neill Dela Llana  7107    NaN
2346        2346        Scott Smith  7108    NaN
2347        2347        Daniel Hsia  7109   Male
2348        2348   Brian Herzlinger  7110   Male

[2349 rows x 4 columns]

In [31]:
df = pd.read_csv("movies.csv",index_col=0)
df.head()

,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday
2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday
5,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday

In [32]:
df1 = pd.read_csv("directors.csv", index_col=0)
df1

          director_name    id gender
0         James Cameron  4762   Male
1        Gore Verbinski  4763   Male
2            Sam Mendes  4764   Male
3     Christopher Nolan  4765   Male
4        Andrew Stanton  4766   Male
...                 ...   ...    ...
2344      Shane Carruth  7106   Male
2345   Neill Dela Llana  7107    NaN
2346        Scott Smith  7108    NaN
2347        Daniel Hsia  7109   Male
2348   Brian Herzlinger  7110   Male

[2349 rows x 3 columns]

In [33]:
df.shape

(1465, 11)

In [41]:
df1.shape

(2349, 3)

In [42]:
###unqiye directors 
df["director_id"].unique()

array([4762, 4763, 4764, 4765, 4767, 4771, 4772, 4773, 4774, 4775, 4776,
       4777, 4779, 4780, 4782, 4785, 4786, 4788, 4791, 4793, 4794, 4797,
       4798, 4799, 4802, 4803, 4804, 4805, 4808, 4809, 4810, 4811, 4812,
       4813, 4814, 4829, 4831, 4832, 4833, 4838, 4839, 4842, 4845, 4846,
       4847, 4849, 4854, 4857, 4858, 4859, 4863, 4865, 4866, 4867, 4868,
       4872, 4873, 4874, 4876, 4880, 4881, 4885, 4886, 4888, 4889, 4890,
       4892, 4893, 4894, 4900, 4904, 4909, 4913, 4915, 4917, 4918, 4921,
       4923, 4924, 4925, 4926, 4927, 4930, 4935, 4936, 4945, 4947, 4948,
       4949, 4955, 4958, 4960, 4964, 4965, 4967, 4974, 4978, 4989, 4991,
       4993, 4995, 4998, 5002, 5005, 5008, 5009, 5014, 5017, 5024, 5031,
       5033, 5034, 5035, 5037, 5039, 5047, 5053, 5056, 5059, 5061, 5067,
       5082, 5087, 5088, 5093, 5096, 5097, 5101, 5105, 5111, 5113, 5115,
       5116, 5123, 5125, 5130, 5132, 5135, 5140, 5147, 5148, 5152, 5157,
       5162, 5179, 5182, 5191, 5193, 5195, 5196, 5202, 5203, 5207, 5217,
       5222, 5226, 5227, 5228, 5229, 5231, 5235, 5249, 5253, 5262, 5265,
       5283, 5292, 5293, 5303, 5307, 5310, 5323, 5338, 5362, 5363, 5367,
       5369, 5375, 5405, 5450, 5451, 5457, 5465, 5489, 5519, 5535, 5549,
       5554, 5599, 5615, 5628, 5697, 5709, 5826, 5894, 5951, 5970, 6056,
       6204])

In [73]:
df["director_id"].isin(df1["id"])

0       True
1       True
2       True
3       True
5       True
        ...
4736    True
4743    True
4748    True
4749    True
4768    True
Name: director_id, Length: 1465, dtype: bool

In [75]:
##np.all will give me true bonly if all the vaues are true
np.all(df["director_id"].isin(df1["id"]))

np.True_

In [76]:
data = df.merge(df1, how="left", left_on="director_id", right_on="id")

In [77]:
data.drop(["director_id", "id_y"], axis=1, inplace=True)

In [47]:
data

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male
2,43599,245000000,107,880674609,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,Male
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1460,48363,0,3,321952,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,Male
1461,48370,27000,19,3151130,Clerks,7.4,755,1994,Sep,Tuesday,Kevin Smith,Male
1462,48375,0,7,0,Rampage,6.0,131,2009,Aug,Friday,Uwe Boll,Male
1463,48376,0,3,0,Slacker,6.4,77,1990,Jul,Friday,Richard Linklater,Male
1464,48395,220000,14,2040920,El Mariachi,6.6,238,1992,Sep,Friday,Robert Rodriguez,NaN

In [78]:
data.describe()

,id_x,budget,popularity,revenue,vote_average,vote_count,year
count,1465.000000,1.465000e+03,1465.000000,1.465000e+03,1465.000000,1465.000000,1465.000000
mean,45225.191126,4.802295e+07,30.855973,1.432539e+08,6.368191,1146.396587,2002.615017
std,1189.096396,4.935541e+07,34.845214,2.064918e+08,0.818033,1578.077438,8.680141
min,43597.000000,0.000000e+00,0.000000,0.000000e+00,3.000000,1.000000,1976.000000
25%,44236.000000,1.400000e+07,11.000000,1.738013e+07,5.900000,216.000000,1998.000000
50%,45022.000000,3.300000e+07,23.000000,7.578164e+07,6.400000,571.000000,2004.000000
75%,45990.000000,6.600000e+07,41.000000,1.792469e+08,6.900000,1387.000000,2009.000000
max,48395.000000,3.800000e+08,724.000000,2.787965e+09,8.300000,13752.000000,2016.000000

In [49]:
data.describe(include=object) ##non numerical data bhi deta hia, on the basiss of exmple: most frequesnt

C:\Users\chitr\AppData\Local\Temp\ipykernel_7384\3170780047.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  data.describe(include=object) ##non numerical data bhi deta hia, on the basiss of exmple: most frequesnt

         title month     day     director_name gender
count     1465  1465    1465              1465   1341
unique    1465    12       7               199      2
top     Avatar   Dec  Friday  Steven Spielberg   Male
freq         1   193     654                26   1309

In [81]:
data["revenue"]  = data["revenue"]/1000000
data["budget"]  = data["budget"]/1000000

In [82]:
###Quering Dataframe to fetch the data
data.loc[data["vote_average"] > 8, ["title", "vote_average"]].head()

                                             title  vote_average
45                                 The Dark Knight           8.2
58                                    Interstellar           8.1
59                                       Inception           8.1
199  The Lord of the Rings: The Return of the King           8.1
383                                     Fight Club           8.3

In [41]:
data[(data["vote_average"] > 7) & (data["year"] >= 2015)].head()

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
30,43641,190000000,102,15062.49360,Furious 7,7.3,4176,2015,Apr,Wednesday,James Wan,Male
78,43724,150000000,434,3788.58340,Mad Max: Fury Road,7.2,9427,2015,May,Wednesday,George Miller,Male
106,43773,135000000,100,5329.50503,The Revenant,7.3,6396,2015,Dec,Friday,Alejandro González Iñárritu,Male
162,43867,108000000,167,6301.61890,The Martian,7.6,7268,2015,Sep,Wednesday,Ridley Scott,Male
312,44128,75000000,48,1081.45109,The Man from U.N.C.L.E.,7.1,2265,2015,Aug,Thursday,Guy Ritchie,Male

In [52]:
data[data["title"].str.contains("Batman")]

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
5,43606,250000000,155,8732.60194,Batman v Superman: Dawn of Justice,5.7,7004,2016,Mar,Wednesday,Zack Snyder,Male
74,43716,150000000,115,3742.18673,Batman Begins,7.5,7359,2005,Jun,Friday,Christopher Nolan,Male
128,43807,125000000,50,2382.07122,Batman & Robin,4.2,1418,1997,Jun,Friday,Joel Schumacher,Male
184,43896,100000000,48,3365.29144,Batman Forever,5.2,1498,1995,May,Wednesday,Joel Schumacher,Male
257,44025,80000000,59,2800.00000,Batman Returns,6.6,1673,1992,Jun,Friday,Tim Burton,Male
704,44956,35000000,44,4113.48924,Batman,7.0,2096,1989,Jun,Friday,Tim Burton,Male

In [53]:
data[data["title"].str.startswith("The")]

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
3,43600,250000000,112,10849.39099,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
9,43610,255000000,49,892.89910,The Lone Ranger,5.9,2311,2013,Jul,Wednesday,Gore Verbinski,Male
11,43612,225000000,53,4196.51413,The Chronicles of Narnia: Prince Caspian,6.3,1630,2008,May,Thursday,Andrew Adamson,Male
14,43616,250000000,120,9560.19788,The Hobbit: The Battle of the Five Armies,7.1,4760,2014,Dec,Wednesday,Peter Jackson,Male
16,43619,250000000,94,9584.00000,The Hobbit: The Desolation of Smaug,7.6,4524,2013,Dec,Wednesday,Peter Jackson,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1435,48095,600000,10,0.00000,The Kentucky Fried Movie,6.4,66,1977,Aug,Wednesday,John Landis,Male
1443,48192,350000,35,294.00000,The Evil Dead,7.3,894,1981,Oct,Thursday,Sam Raimi,Male
1449,48244,250000,6,0.56825,The Canyons,4.1,75,2013,Jul,Monday,Paul Schrader,NaN
1457,48323,0,5,0.00000,The Mighty,7.1,51,1998,Oct,Friday,Peter Chelsom,Male
1460,48363,0,3,3.21952,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,Male

In [45]:
data.sort_values("popularity", ascending=False).head()

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
58,43692,165000000,724,6751.20017,Interstellar,8.1,10867,2014,Nov,Wednesday,Christopher Nolan,Male
78,43724,150000000,434,3788.58340,Mad Max: Fury Road,7.2,9427,2015,May,Wednesday,George Miller,Male
119,43796,140000000,271,6550.11224,Pirates of the Caribbean: The Curse of the Bla...,7.5,6985,2003,Jul,Wednesday,Gore Verbinski,Male
120,43797,125000000,206,7521.00229,The Hunger Games: Mockingjay - Part 1,6.6,5584,2014,Nov,Tuesday,Francis Lawrence,Male
45,43662,185000000,187,10045.58444,The Dark Knight,8.2,12002,2008,Jul,Wednesday,Christopher Nolan,Male

In [54]:
data.loc[data["director_name"] == "Christopher Nolan", "title"]

3       The Dark Knight Rises
45            The Dark Knight
58               Interstellar
59                  Inception
74              Batman Begins
565                  Insomnia
641              The Prestige
1341                  Memento
Name: title, dtype: str

In [55]:
##how to display no of movies by every director
data["director_name"].value_counts()

director_name
Steven Spielberg       26
Martin Scorsese        19
Clint Eastwood         19
Woody Allen            18
Ridley Scott           16
                       ..
Mike Leigh              5
Brad Anderson           5
Michael Polish          5
Darren Lynn Bousman     5
Nicole Holofcener       5
Name: count, Length: 199, dtype: int64

In [72]:
##higest budgest mivies directed by evey director

data.loc[data["budget"]]

KeyError: '[237000000, 300000000, 245000000, 250000000, 258000000, 270000000, 200000000, 255000000, 225000000, 380000000, 180000000, 207000000, 209000000, 210000000, 150000000, 190000000, 195000000, 185000000, 140000000, 176000003, 178000000, 170000000, 145000000, 175000000, 165000000, 160000000, 38000000, 155000000, 70000000, 139000000, 135000000, 130000000, 137000000, 120000000, 132000000, 110000000, 125000000, 127000000, 65000000, 123000000, 117000000, 115000000, 116000000, 105000000, 93000000, 107000000, 133000000, 108000000, 126000000, 90000000, 103000000, 102000000, 100000000, 80000000, 94000000, 92000000, 95000000, 79000000, 98000000, 75000000, 88000000, 68000000, 85000000, 84000000, 82500000, 8000000, 82000000, 86000000, 60000000, 78000000, 76000000, 73000000, 50000000, 53000000, 72500000, 72000000, 66000000, 36000000, 69000000, 63000000, 52000000, 45000000, 64000000, 62000000, 44000000, 61000000, 58000000, 55000000, 35000000, 58800000, 83000000, 57000000, 56000000, 54000000, 30000000, 47000000, 46000000, 67000000, 51000000, 48000000, 40000000, 51500000, 49900000, 22000000, 49000000, 43000000, 25000000, 42000000, 32000000, 31000000, 33000000, 41000000, 10000000, 15000000, 39000000, 80341000, 37000000, 1800000, 34000000, 27000000, 31500000, 30250000, 34200000, 18000000, 28000000, 29000000, 21000000, 27500000, 26000000, 25100000, 2800000, 20000000, 14000000, 24000000, 17000000, 23000000, 19000000, 12500000, 9000000, 13000000, 19800000, 12000000, 8700000, 19100000, 18500000, 16500000, 1000000, 3500000, 16000000, 300000, 7000000, 11500000, 14600000, 11000000, 5000000, 10500000, 6000000, 13800000, 12305523, 40600000, 8500000, 6500000, 7500000, 6900000, 6400000, 134005, 5952000, 4000000, 4500000, 4200000, 3705538, 1300000, 3800000, 3600000, 2700000, 3000000, 2000000, 2500000, 2400000, 13500000, 1530000, 1500000, 1350000, 1250000, 1200000, 600000, 500000, 860000, 350000, 312000, 250000, 400000, 200000, 150000, 160000, 10000, 60000, 27000, 220000] not in index'

In [57]:
data.groupby("director_name")["budget"].max() ##this gives a groupby object

director_name
Adam McKay                     100000000
Adam Shankman                   80000000
Alejandro González Iñárritu    135000000
Alex Proyas                    140000000
Alexander Payne                 30000000
                                 ...
Wes Craven                      40000000
Wolfgang Petersen              175000000
Woody Allen                     30000000
Zack Snyder                    250000000
Zhang Yimou                     94000000
Name: budget, Length: 199, dtype: int64

In [58]:
##which director is most productive director
##-no of movioes, qualit etc
data.groupby("director_name")["title"].count().sort_values(ascending=False)

director_name
Steven Spielberg    26
Martin Scorsese     19
Clint Eastwood      19
Woody Allen         18
Robert Rodriguez    16
                    ..
Stephen Daldry       5
Tom Tykwer           5
Tim Hill             5
Uwe Boll             5
Wayne Wang           5
Name: title, Length: 199, dtype: int64

In [59]:
##avergae no of movies per year
# active_year = last_workingyear - firstworkingywae

df_agg = data.groupby("director_name")[["year","title"]].aggregate({"year":["min", "max"], "title":["count"]})


##

In [60]:
df_agg.columns

MultiIndex([( 'year',   'min'),
            ( 'year',   'max'),
            ('title', 'count')],
           )

In [61]:
df_agg.columns = ["_".join(col) for col in df_agg.columns]

In [63]:
df_agg.columns

Index(['year_min', 'year_max', 'title_count'], dtype='str')

In [64]:
df_agg

                             year_min  year_max  title_count
director_name
Adam McKay                       2004      2015            6
Adam Shankman                    2001      2012            8
Alejandro González Iñárritu      2000      2015            6
Alex Proyas                      1994      2016            5
Alexander Payne                  1999      2013            5
...                               ...       ...          ...
Wes Craven                       1984      2011           10
Wolfgang Petersen                1981      2006            7
Woody Allen                      1977      2013           18
Zack Snyder                      2004      2016            7
Zhang Yimou                      2002      2014            6

[199 rows x 3 columns]

In [62]:
df_agg.reset_index(inplace=True) ##3rest index stariting with zero

In [64]:
df_agg["active_yes"] = df_agg["year_max"] - df_agg["year_min"]

In [65]:
df_agg

                   director_name  year_min  year_max  title_count  active_yes
0                     Adam McKay      2004      2015            6          11
1                  Adam Shankman      2001      2012            8          11
2    Alejandro González Iñárritu      2000      2015            6          15
3                    Alex Proyas      1994      2016            5          22
4                Alexander Payne      1999      2013            5          14
..                           ...       ...       ...          ...         ...
194                   Wes Craven      1984      2011           10          27
195            Wolfgang Petersen      1981      2006            7          25
196                  Woody Allen      1977      2013           18          36
197                  Zack Snyder      2004      2016            7          12
198                  Zhang Yimou      2002      2014            6          12

[199 rows x 5 columns]

In [66]:
df_agg["movie_per_yr"] = df_agg["title_count"] / df_agg["active_yes"]

In [67]:
df_agg

,director_name,year_min,year_max,title_count,active_yes,movie_per_yr
0,Adam McKay,2004,2015,6,11,0.545455
1,Adam Shankman,2001,2012,8,11,0.727273
2,Alejandro González Iñárritu,2000,2015,6,15,0.400000
3,Alex Proyas,1994,2016,5,22,0.227273
4,Alexander Payne,1999,2013,5,14,0.357143
...,...,...,...,...,...,...
194,Wes Craven,1984,2011,10,27,0.370370
195,Wolfgang Petersen,1981,2006,7,25,0.280000
196,Woody Allen,1977,2013,18,36,0.500000
197,Zack Snyder,2004,2016,7,12,0.583333
198,Zhang Yimou,2002,2014,6,12,0.500000

In [68]:
df_agg.sort_values("movie_per_yr",ascending=False).head()

,director_name,year_min,year_max,title_count,active_yes,movie_per_yr
190,Tyler Perry,2006,2013,9,7,1.285714
73,Jason Friedberg,2006,2010,5,4,1.250000
169,Shawn Levy,2002,2014,11,12,0.916667
158,Robert Rodriguez,1992,2014,16,22,0.727273
1,Adam Shankman,2001,2012,8,11,0.727273

In [69]:
df_agg.sort_values(["year_min","year_max"], ascending=[True, False])

,director_name,year_min,year_max,title_count,active_yes,movie_per_yr
115,Martin Scorsese,1976,2013,19,37,0.513514
148,Richard Donner,1976,2006,11,30,0.366667
170,Sidney Lumet,1976,2006,5,30,0.166667
179,Steven Spielberg,1977,2016,26,39,0.666667
196,Woody Allen,1977,2013,18,36,0.500000
...,...,...,...,...,...,...
190,Tyler Perry,2006,2013,9,7,1.285714
73,Jason Friedberg,2006,2010,5,4,1.250000
52,Francis Lawrence,2007,2015,5,8,0.625000
91,Jon M. Chu,2008,2016,5,8,0.625000
130,Nicholas Stoller,2008,2016,5,8,0.625000

In [ ]:
##group based filtering-- filtering rows, but basee on group based property

##filtering all rows (movies ) which are diredcted by high budget directors

##print all the movies od the director who has the high budget

In [86]:
##find name of directors who have diredted 100m mivid
df_dir_budget =  data.groupby("director_name")["budget"].max().reset_index()

In [88]:
df_dir_budget

                   director_name  budget
0                     Adam McKay   100.0
1                  Adam Shankman    80.0
2    Alejandro González Iñárritu   135.0
3                    Alex Proyas   140.0
4                Alexander Payne    30.0
..                           ...     ...
194                   Wes Craven    40.0
195            Wolfgang Petersen   175.0
196                  Woody Allen    30.0
197                  Zack Snyder   250.0
198                  Zhang Yimou    94.0

[199 rows x 2 columns]

In [91]:
df_dir_budget.loc[df_dir_budget["budget"] >= 100, "director_name"]

0                       Adam McKay
2      Alejandro González Iñárritu
3                      Alex Proyas
5                   Andrew Adamson
10                         Ang Lee
                  ...
187                    Tom Shadyac
188                     Tom Tykwer
189                     Tony Scott
195              Wolfgang Petersen
197                    Zack Snyder
Name: director_name, Length: 85, dtype: str

In [96]:
data.groupby("director_name").filter(lambda x: x["budget"].max() >= 100)

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237.00,150,2.787965e-08,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43598,300.00,139,9.610000e-09,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male
2,43599,245.00,107,8.806746e-09,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,Male
3,43600,250.00,112,1.084939e-08,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
4,43602,258.00,115,8.908716e-09,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1450,48267,0.40,33,1.000000e-09,Mad Max,6.6,1213,1979,Apr,Thursday,George Miller,Male
1451,48268,0.20,13,4.505922e-11,Swingers,6.8,253,1996,Oct,Friday,Doug Liman,Male
1452,48274,0.00,5,2.611555e-11,Three,6.3,31,2010,Dec,Thursday,Tom Tykwer,Male
1458,48335,0.06,27,3.221152e-11,Pi,7.1,586,1998,Jul,Friday,Darren Aronofsky,Male
1460,48363,0.00,3,3.219520e-12,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,Male

In [97]:
data.groupby("director_name").filter(lambda x: x["budget"].max() >= 100)["director_name"].unique()

<StringArray>
[              'James Cameron',              'Gore Verbinski',
                  'Sam Mendes',           'Christopher Nolan',
                   'Sam Raimi',                 'Zack Snyder',
                'Bryan Singer',                'Marc Forster',
              'Andrew Adamson',                'Rob Marshall',
            'Barry Sonnenfeld',               'Peter Jackson',
                'Ridley Scott',                 'Chris Weitz',
                  'Peter Berg',                  'Tim Burton',
                'Brett Ratner',                 'Michael Bay',
             'Martin Campbell',                         'McG',
                   'James Wan',                 'Mike Newell',
          'Guillermo del Toro',            'Steven Spielberg',
                  'Justin Lin',             'Roland Emmerich',
             'Robert Zemeckis',             'Lilly Wachowski',
                 'Jon Favreau',             'Martin Scorsese',
                   'Rob Cohen',                  'David Ayer',
                 'Tom Shadyac',                  'Doug Liman',
              'Kevin Reynolds',               'David Fincher',
            'Francis Lawrence',              'Jon Turteltaub',
           'Wolfgang Petersen',               'Michael Apted',
                'Oliver Stone',                  'Shawn Levy',
               'George Miller',                  'Ron Howard',
             'Kenneth Branagh',          'Jonathan Liebesman',
          'M. Night Shyamalan',                  'Joe Wright',
                 'Rob Minkoff',                'Lee Tamahori',
                'Edward Zwick',                 'Alex Proyas',
              'Richard Donner',                     'Ang Lee',
                  'Jon M. Chu',                 'Bill Condon',
             'Louis Leterrier', 'Alejandro González Iñárritu',
             'Paul Greengrass',               'Phillip Noyce',
            'Darren Aronofsky',              'Chris Columbus',
            'Robert Schwentke',                 'Guy Ritchie',
              'Paul Verhoeven',              'John McTiernan',
             'Joel Schumacher',                    'John Woo',
                   'Tim Story',               'James Mangold',
             'Roger Donaldson',           'Steven Soderbergh',
                'Raja Gosnell',                 'Jan de Bont',
                'Frank Coraci',                'Michael Mann',
                  'Tony Scott',                  'Paul Weitz',
                  'Adam McKay',               'Chuck Russell',
           'Quentin Tarantino',                  'Simon West',
                 'Peter Hyams',                  'Tom Tykwer',
          'Paul W.S. Anderson']
Length: 85, dtype: str

In [ ]:
##group based trasformation

##Feature/coulumn Transformation -- Budget/ Revenue dollars -> m dollars

In [ ]:
##asses every movie wrt to director avergare budget
# def Subtract_avg(x):
#     x["additional_budget"] = x["budget"] - x["budget"].mean()

# def inspect(x):
#     print(x)
#     print(type(x))
#     raise


data.groupby("director_name").transform(inspect)

TypeError: Cannot perform reduction 'mean' with string dtype

In [ ]:
def Subtract_avg(x):
    return x - x.mean()

##transform works with seriess


data["additional_budget"] = data.groupby("director_name")["budget"].transform(Subtract_avg)
data

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,additional_budget
0,43597,237.000,150,2.787965e-08,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male,130.300000
1,43598,300.000,139,9.610000e-09,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male,141.857143
2,43599,245.000,107,8.806746e-09,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,Male,150.142857
3,43600,250.000,112,1.084939e-08,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male,124.375000
4,43602,258.000,115,8.908716e-09,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,Male,174.004545
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,48363,0.000,3,3.219520e-12,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,Male,-47.478947
1461,48370,0.027,19,3.151130e-11,Clerks,7.4,755,1994,Sep,Tuesday,Kevin Smith,Male,-11.979417
1462,48375,0.000,7,0.000000e+00,Rampage,6.0,131,2009,Aug,Friday,Uwe Boll,Male,-21.700000
1463,48376,0.000,3,0.000000e+00,Slacker,6.4,77,1990,Jul,Friday,Richard Linklater,Male,-10.890909
1464,48395,0.220,14,2.040920e-11,El Mariachi,6.6,238,1992,Sep,Friday,Robert Rodriguez,NaN,-31.168750

In [113]:
##for ba movie, if it was risky for a director or not---whose buget was even higher than average revenue of the moviee director by same director

def func(x):
    x["risky"] = x["budget"] - x["revenue"].mean() >= 0
    return x

    
df_risky =   data.groupby("director_name").apply(func)

In [114]:
df_risky.loc[df_risky["risky"] == True]

                    id_x     budget  popularity       revenue  \
director_name
Adam McKay    176  43882  100.00000          24  1.704329e-09
              323  44151   72.50000          12  1.629662e-09
              366  44236   65.00000          22  1.281076e-09
              505  44503   50.00000          38  1.736490e-09
              839  45301   28.00000          57  1.333465e-09
...                  ...        ...         ...           ...
Zack Snyder   396  44284   65.00000          65  4.226104e-09
              842  45304   28.00000          44  1.023564e-09
Zhang Yimou   192  43914   94.00000          12  9.531143e-10
              590  44692    0.00011           9  0.000000e+00
              604  44733   31.00000          23  1.773944e-09

                                                         title  vote_average  \
director_name
Adam McKay    176                               The Other Guys           6.1
              323  Talladega Nights: The Ballad of Ricky Bobby           6.2
              366                                Step Brothers           6.5
              505            Anchorman 2: The Legend Continues           6.0
              839                                The Big Short           7.3
...                                                        ...           ...
Zack Snyder   396                                          300           7.0
              842                             Dawn of the Dead           6.8
Zhang Yimou   192                           The Flowers of War           7.1
              590                   Curse of the Golden Flower           6.6
              604                                         Hero           7.2

                   vote_count  year month        day gender  \
director_name
Adam McKay    176        1383  2010   Aug     Friday   Male
              323         491  2006   Aug     Friday   Male
              366        1062  2008   Jul     Friday   Male
              505         923  2013   Dec  Wednesday   Male
              839        2607  2015   Dec     Friday   Male
...                       ...   ...   ...        ...    ...
Zack Snyder   396        4997  2006   Dec   Saturday   Male
              842        1016  2004   Mar     Friday   Male
Zhang Yimou   192         187  2011   Dec   Thursday   Male
              590         203  2006   Dec   Thursday   Male
              604         635  2002   Dec   Thursday   Male

                   additional_budget  risky
director_name
Adam McKay    176          43.083333   True
              323          15.583333   True
              366           8.083333   True
              505          -6.916667   True
              839         -28.916667   True
...                              ...    ...
Zack Snyder   396         -57.857143   True
              842         -94.857143   True
Zhang Yimou   192          73.166648   True
              590         -20.833242   True
              604          10.166648   True

[1329 rows x 13 columns]

In [ ]:
##aggregate -- for all rows, group based
##filering -- values in rows, based same group based properties
## transformation - values in rows ,or groupt based properties do that transformation